// flow-typed signature: ce4d3cc196d42e941e093d353ec8e17c
// flow-typed version: <<STUB>>/react-p5-wrapper_v2.0.0/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-p5-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-p5-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-p5-wrapper/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-p5-wrapper/dist/index.js' {
  declare module.exports: $Exports<'react-p5-wrapper/dist/index'>;
}
